#ifndef PHOTOMETRICPLUGIN_GLOBAL_H
#define PHOTOMETRICPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PHOTOMETRICPLUGIN_LIBRARY)
#  define PHOTOMETRICPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define PHOTOMETRICPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PHOTOMETRICPLUGIN_GLOBAL_H
