#ifndef PCBDETECT_PLUGIN_GLOBAL_H
#define PCBDETECT_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PCBDETECT_PLUGIN_LIBRARY)
#  define PCBDETECT_PLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define PCBDETECT_PLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // PCBDETECT_PLUGIN_GLOBAL_H
