#ifndef CONTOURPLUGIN_GLOBAL_H
#define CONTOURPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONTOURPLUGIN_LIBRARY)
#  define CONTOURPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define CONTOURPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // CONTOURPLUGIN_GLOBAL_H
